### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [gynvael/arcanesector#2]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by gynvael** [comment]
Hey,
Unless specified otherwise (third party components, credits.txt, etc), please assume it's a MIT-like licence limited to non-commercial use only. I.e. feel free to study it, run & modify it for your own enjoyment, or use it for free CTFs you would hosts (as long as you don't do it commercially).
